# Generated by Django 5.2 on 2026-01-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_pokemon_image_alter_pokemon_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='Lon')),
                ('latitude', models.FloatField(verbose_name='Lat')),
            ],
        ),
    ]
