# Generated by Django 5.2 on 2026-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_pokemonentity_appeared_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon_def',
            field=models.IntegerField(null=True, verbose_name='Defence'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon_hlth',
            field=models.IntegerField(null=True, verbose_name='Health'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon_lvl',
            field=models.IntegerField(null=True, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon_stam',
            field=models.IntegerField(null=True, verbose_name='Stamina'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon_strength',
            field=models.IntegerField(null=True, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
