# Generated by Django 5.2 on 2026-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemon_img_url_pokemonentity_pokemon_def_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
