# Generated by Django 5.2 on 2026-03-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemonentity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='name',
        ),
    ]
