# Generated by Django 5.2 on 2026-05-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_alter_pokemon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_image',
            new_name='image',
        ),
    ]
