# Generated by Django 5.2 on 2026-05-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_rename_pokemon_image_pokemon_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_def',
            new_name='defence',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_hlth',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_lvl',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_stam',
            new_name='stamina',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='pokemon_strength',
            new_name='strength',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='subject',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='Покемон'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Английское название'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Японское название'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]