# Generated by Django 5.2 on 2026-05-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_rename_pokemon_def_pokemonentity_defence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='img_url',
        ),
    ]
